CREATE TABLE IF NOT EXISTS ORDERS(
    ID BIGINT PRIMARY KEY,
    DT DATE NOT NULL,
    FLG_PAY BOOLEAN NOT NULL DEFAULT FALSE,
    FLG_RECEIVE BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS CART_CURRENT(
    ID_PRODUCT BIGINT REFERENCES products(id)
);
CREATE TABLE IF NOT EXISTS CART_ACCOMPLISHED(
    ID_ORDER BIGINT REFERENCES ORDERS(ID),
    ID_PRODUCT BIGINT REFERENCES products(id)
);