CREATE TABLE IF NOT EXISTS USERS(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    ENABLED BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS ROLES(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE
);
CREATE TABLE IF NOT EXISTS USERS_ROLES(
    ID_USER BIGINT NOT NULL REFERENCES USERS(ID),
    ID_ROLE BIGINT NOT NULL REFERENCES ROLES(ID),
    CONSTRAINT SECURITY_USER_ROLE UNIQUE(ID_USER, ID_ROLE)
);
