CREATE TABLE IF NOT EXISTS USERS(
    USERNAME VARCHAR(255) PRIMARY KEY,
    PASSWORD VARCHAR(255) NOT NULL,
    ENABLED BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS AUTHORITIES(
    USERNAME VARCHAR(255) NOT NULL REFERENCES USERS(USERNAME),
    AUTHORITY VARCHAR(255) NOT NULL,
    CONSTRAINT CONS_UNQ_AUTHORITIES UNIQUE(USERNAME, AUTHORITY)
);