INSERT INTO USERS(NAME, PASSWORD, ENABLED)
VALUES('user', '$2a$12$M7vhWnv1bdfBkQHQQsPYhuqrSUCCK3a3DZHU5J3UKRy05qxWI3e0C', true);
INSERT INTO USERS(NAME, PASSWORD, ENABLED)
VALUES('admin', '$2a$12$/l5/xR1Pl9BFk5SJ5an.peAE.KnmOoiTfCaceu3dE/qBs8Cn1bW1G', true);
INSERT INTO USERS(NAME, PASSWORD, ENABLED)
VALUES('manager', '$2a$12$F2OkR2R3R9HcEBPt0eNNJuKVuA.ICCcJ0g19zEJL6QtFHNZwfu5w2', true);

INSERT INTO ROLES(NAME) VALUES('ROLE_USER');
INSERT INTO ROLES(NAME) VALUES('ROLE_ADMIN');
INSERT INTO ROLES(NAME) VALUES('ROLE_MANAGER');

INSERT INTO USERS_ROLES VALUES(1, 1);
INSERT INTO USERS_ROLES VALUES(2, 1);
INSERT INTO USERS_ROLES VALUES(2, 2);
INSERT INTO USERS_ROLES VALUES(2, 3);
INSERT INTO USERS_ROLES VALUES(3, 1);
INSERT INTO USERS_ROLES VALUES(3, 3);